n = str(input("enter a string"))
a = str(input("enter value to strip from left"))
b = str(input("enter value to strip from right"))
print(n)
print(len(n))
print(n.upper())
print(n.lower())
print(n.isupper())
print(n.islower())
print(n.lstrip(a))
print(n.rstrip(b))